[facebook]
page_access_token = "EAAOBMtxoGREBO4lZB7NN0OgQuzmRgkTKRcvnGaTUti2lmbENOcZBJlgFbmz4SGD0YEz1v9MJev0OeJtqMtffEdCZCyX7X4FKyGsInKaDYttltKdT2ZAK4fDgR90EYUm5Vg09aNO0O5lYdjOQWUbdmdsqN4jzRjOF0OvwPPABLS81qsZBZAE44E6QZDZD"
user_token = "EAAOBMtxoGREBO8lLH79ZCfK7C99DlDhRQ7agns5PbDZCSsoCplwwSfJ7oeeQNWs4gSUgn4zrb6QaV4ZCMcMmOsk6NZBei0S0VWeU3ZCf2wiZAboyM6ws9VT8Oxa8SXzrvny2UT5KxjcEFD4h4KHVqsBcpBIshPZBTbvyp0bvGsWKsAtyegXskCpKAZDZD"
api_version = "v20.0"
